#!/usr/bin/python
## Pombert Lab 2022


name = 'create_conserved_figure.py'
version = '0.1a'
updated = '2022-04-11'
usage = f'''
NAME		{name}
VERSION		{version}
UPDATED		{updated}
SYNOPSIS	This script creates a figure depicting the conservation of proteins between organisms.

USAGE		{name} \\
		  

OPTIONS
-c (--con_sum)	Directory containing conserved_summary files generated by id_conserved.pl
-o (--out)	File name to save figure under [Default: conserved_figure]
-f (--format)	Save format (.png,.eps,.jpg,.jpeg,.pdf,.pgf,.ps,.raw,.rgba,.svg,.svgz,.tif,.tiff) [Default: .svg]
'''

from enum import unique
from xml.sax.handler import all_properties
from matplotlib import pyplot as plt
from sys import argv
import argparse as ap
from os import listdir,path
import re

if(len(argv) <= 1):
	print(usage)
	exit()


parser = ap.ArgumentParser()
parser.add_argument('-c','--con_sum',required=True)
parser.add_argument('-o','--out',default="conserved_figure")
parser.add_argument('-f','--format',default=[".svg"])

args = parser.parse_args()

conserved_file = args.con_sum
out = args.out
format_types = args.format

all_proteins = []
unique_proteins = []
conserved_proteins = []
protein_counter = 0

organism = ""

with open(conserved_file,"r") as FILE:
	for line in FILE:
		if "###" in line:
			organism = re.search("^###\s+(\S+)",line).groups(0)[0]
		else:
			line = line.replace("\n","")
			info = line.split("\t")
			all_proteins.append(info[0])
			if "0" not in info[1] and "1" not in info[1]:
				conserved_proteins.append(protein_counter)
			elif "1" not in info[1] and "2" not in info[1]:
				unique_proteins.append(protein_counter)
			protein_counter += 1


y = [i for i in range(len(all_proteins))]
skipped = int(len(all_proteins)*.1)
ticks = [i for i in range(0,len(all_proteins),skipped)]
tick_lables = [all_proteins[i] for i in range(0,len(all_proteins),skipped)]

fig, ax = plt.subplots()

ax.eventplot(conserved_proteins,orientation="vertical",lineoffsets=0,colors="#939598",linelengths=.25)
ax.eventplot(unique_proteins,orientation="vertical",lineoffsets=-.125,colors="#8ad8d0",linelengths=.25)
# ax.eventplot(conserved.values(),orientation="vertical",lineoffsets=[.125 for i in range(0,len(organisms))],color=["#d27061","#e9a746"],linelengths=.25)
labels = ["Conserved between all",f"Proteins unique to {organism}"]
# for org in organisms:
# 	labels.append(f"Conserved with {org}")
ax.legend(labels)
ax.set_xlim(-1,1)
ax.set_yticks(ticks)
ax.set_yticklabels(tick_lables)

plt.show()

# for format_type in format_types:
# 	format_type = format_type.replace(".","")
# 	plt.savefig(f"{out}.{format_type}",format=format_type,transparent=True)

